import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";

import "./globals.css";
import React from "react";
import { LanguageProvider } from "@/lib/language-context";
import { LanguageSelector } from "@/components/LanguageSelector";

export const metadata: Metadata = {
  title: "CV - Juan Carlos Lopez Palos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <LanguageProvider>
          <LanguageSelector />
          {children}
        </LanguageProvider>
      </body>
      <Analytics />
    </html>
  );
}
